function exportData(name,data){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}

function featureTable(rows,keys){return '<div class="table-wrap"><table><thead><tr>'+keys.map(k=>'<th>'+esc(k)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+keys.map(k=>'<td>'+esc(typeof r[k]==='object'?JSON.stringify(r[k]):r[k])+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>'}

function siteLink(id,dest){localStorage.setItem('mineos-site',id);location.href=dest+'.html'}

async function executiveGrid(){const d=await api('/executive');$('#content').insertAdjacentHTML('beforeend',`<section class="panel"><h2>Site register</h2><div class="metrics">${metric('Shift reports today',d.totals.reporting_sites+'/'+d.totals.total_sites)}${metric('Actual production',d.totals.reporting_sites?num(d.totals.actual_mt)+' MT':'No shift log')}${metric('Production target',d.totals.reporting_sites?num(d.totals.target_mt)+' MT':'No shift log')}</div><div class="row"><input id="site-search" placeholder="Search site"><select id="site-filter"><option value="all">All sites</option><option value="attention">Needs review</option><option>Underground</option><option>Opencast</option></select><button id="executive-export">Export register</button></div><div id="site-grid" class="grid"></div></section>`);const draw=()=>{$('#site-grid').innerHTML=d.sites.filter(s=>s.name.toLowerCase().includes($('#site-search').value.toLowerCase())&&($('#site-filter').value==='all'||($('#site-filter').value==='attention'?s.attention:s.mine_type===$('#site-filter').value))).map(s=>`<article class="panel"><h3>${esc(s.name)}</h3>${badge(s.reported_shifts===0?'Awaiting shift log':s.attention?'Review':'On track')}<p>Today actual / target: ${s.reported_shifts?num(s.actual_mt)+" / "+num(s.target_mt)+" MT":"No shift log"}<br>Reported Mn grade: ${esc(s.grade_reported||'No record')}<br>Fleet available ${num(s.availability_pct)}% · ${s.inspect} for review<br>Sensor alerts: ${s.alerts.length}</p><button data-site="${s.id}" data-dest="maintenance">View fleet</button><button data-site="${s.id}" data-dest="production">Production plan</button></article>`).join('');$('#site-grid').querySelectorAll('[data-site]').forEach(b=>b.onclick=()=>siteLink(b.dataset.site,b.dataset.dest))};$('#site-search').oninput=draw;$('#site-filter').onchange=draw;$('#executive-export').onclick=()=>exportData('site-register',d);draw()}
function traceLine(rows,key,color){const values=rows.map(r=>Number(r[key])),max=Math.max(1,...values);return `<svg viewBox="0 0 700 130" role="img" aria-label="${esc(key)} chronological chart"><polyline fill="none" stroke="${color}" stroke-width="2" points="${values.map((v,i)=>`${i*700/Math.max(1,values.length-1)},${125-v/max*120}`).join(' ')}"/></svg><small>${esc(key)} · scale 0–${num(max)}</small>`}

async function sensorPanel(){if(!state.selected)return;const d=await api('/telemetry/'+state.selected);let host=$('#sensor-panel');if(!host){host=document.createElement('div');host.id='sensor-panel';$('#content').append(host)}host.innerHTML=`<section class="panel"><h2>Sensor observations</h2>${featureTable(d.measurements,['node_id','kind','value','observed_at','source','operator','alert'])}${['soil_moisture_pct','factor_of_safety','pore_pressure_kpa','inflow_gpm','discharge_gpm','cycle_minutes'].map(kind=>{const rows=d.measurements.filter(r=>r.kind===kind).sort((a,b)=>Date.parse(a.observed_at)-Date.parse(b.observed_at));return rows.length?'<h3>'+esc(kind)+'</h3>'+traceLine(rows,'value','#7c65d6')+'<p>'+esc(rows[0].observed_at)+' to '+esc(rows.at(-1).observed_at)+'</p>':''}).join('')}<p>${d.measurements.length?d.measurements.length+' readings recorded':'No sensor readings recorded for this site.'}</p><details><summary>Add a sourced observation</summary><form id="sensor-form"><div class="form-grid"><label>Node ID<input name="node_id" required minlength="2"></label><label>Measurement<select name="kind">${['rainfall_mm_h','soil_moisture_pct','pore_pressure_kpa','factor_of_safety','inflow_gpm','discharge_gpm','cycle_minutes','battery_pct','signal_dbm'].map(k=>`<option>${k}</option>`).join('')}</select></label><label>Value in named units<input name="value" type="number" step="any" required></label><label>Observation time (local)<input name="observed_at" type="datetime-local" required></label><label>Source reference<input name="source" minlength="5" required></label><label>Operator<input name="operator" minlength="2" required></label>${['latitude','longitude','screening_radius_m','alert_above','alert_below'].map(k=>`<label>${k}<input name="${k}" type="number" step="any"></label>`).join('')}</div><button>Save observation</button><p id="sensor-status"></p></form></details></section>`;$('#sensor-form').onsubmit=async e=>{e.preventDefault();const body={};for(const [k,v] of new FormData(e.target))if(v!=='')body[k]=e.target.elements[k].type==='number'?Number(v):v;body.observed_at=new Date(body.observed_at).toISOString();try{await api('/measurements/'+state.selected,body);await sensorPanel()}catch(err){$('#sensor-status').textContent=err.message}}}
async function replayPanel(){if(!state.selected)return;const d=await api('/telemetry/'+state.selected);$('#content').insertAdjacentHTML('beforeend',`<details class="panel"><summary>Recorded production replay and weather correlation</summary><section class="panel"><p>${esc(d.source)}</p><button id="play-replay">Play dataset replay</button><button id="telemetry-export">Export</button><input id="replay-position" type="range" min="1" max="${d.series.length}" value="${d.series.length}"><div id="telemetry-chart"></div><p>Rainfall / production Pearson correlation: ${num(d.correlation,3)} (descriptive only).</p></section></details>`);const draw=()=>{const rows=d.series.slice(0,Number($('#replay-position').value));$('#telemetry-chart').innerHTML='<p>Through '+esc(rows.at(-1).date)+' '+esc(rows.at(-1).shift)+'</p>'+traceLine(rows,'rainfall_mm','#5793c4')+traceLine(rows,'actual_mt','#388b69')+traceLine(rows,'target_mt','#ae7346')};draw();$('#replay-position').oninput=draw;$('#play-replay').onclick=()=>{if(state.replayTimer){clearInterval(state.replayTimer);state.replayTimer=null;$('#play-replay').textContent='Play dataset replay';return}$('#replay-position').value=1;draw();$('#play-replay').textContent='Pause replay';state.replayTimer=setInterval(()=>{const p=$('#replay-position');p.value=Math.min(Number(p.value)+1,d.series.length);draw();if(Number(p.value)===d.series.length){clearInterval(state.replayTimer);state.replayTimer=null;$('#play-replay').textContent='Replay complete'}},1000)};$('#telemetry-export').onclick=()=>exportData('telemetry-'+state.selected,d);}

async function explorationLayers(){const map=state.map;if(!map)return;const [d,f]=await Promise.all([api('/executive'),api('/operational/equipment')]);const fleetLayer=L.layerGroup(),sensors=L.layerGroup(),buffers=L.layerGroup();f.machines.forEach(m=>L.circleMarker([m.latitude,m.longitude],{radius:3,color:m.status==='inspect'?'#d44949':'#409e75'}).bindPopup(esc(m.id)+'<br>'+esc(m.mapping_source)+'<br>Benchmark risk '+num(m.risk_score*100)+'%').addTo(fleetLayer));d.sites.forEach(s=>Object.values(s.telemetry).forEach(r=>{if(r.latitude==null)return;L.circleMarker([r.latitude,r.longitude],{color:'#7c65d6',radius:5}).bindPopup(esc(r.kind)+': '+num(r.value)+'<br>'+esc(r.observed_at)+'<br>'+esc(r.source)).addTo(sensors);if(r.screening_radius_m)L.circle([r.latitude,r.longitude],{radius:r.screening_radius_m,color:'#e29b34',fillOpacity:.08}).addTo(buffers)}));L.control.layers(null,{'Fleet locations':fleetLayer,'Recorded sensors':sensors,'Screening radii':buffers}).addTo(map);$('#exploration-map').insertAdjacentHTML('afterend','<p class="muted">Map layers: fleet locations, recorded sensor nodes and screening radii. Screening radii and mapped coordinates are available in the selected layers.</p>')}

async function comparisonPanel(){if(!state.selected)return;$('#content').insertAdjacentHTML('beforeend',`<section class="panel"><h2>Baseline versus scenario</h2><p>Production model with rainfall, delay and availability scenarios.</p><form id="compare-form"><div class="row">${[0,15,45,95].map(n=>`<button type="button" data-rain="${n}">${n} mm/day</button>`).join('')}</div><div class="form-grid">${[['rainfall_mm','Daily rain mm',0,500,0],['blast_delay_hours','Blast delay h/shift',0,8,0],['equipment_downtime_hours','Equipment downtime h/shift',0,8,0],['fleet_available_pct_override','Fleet availability %',0,100,100],['fleet_risk_pct_override','Fleet risk %',0,100,0]].map(([k,l,min,max,v])=>`<label>${l}<input name="${k}" type="number" min="${min}" max="${max}" value="${v}" step="any" required></label>`).join('')}</div><button>Compare model scenarios</button><button type="button" id="apply-comparison">Apply to production</button><div id="compare-result"></div></form></section>`);const form=$('#compare-form');form.querySelectorAll('[data-rain]').forEach(b=>b.onclick=()=>form.elements.rainfall_mm.value=b.dataset.rain);const options=()=>({...readScenario(),...Object.fromEntries([...new FormData(form)].map(([k,v])=>[k,Number(v)])),mode:'forecast',simulate_events:false});form.onsubmit=async e=>{e.preventDefault();$('#compare-result').textContent='Calculatingâ€¦';try{const d=await api('/compare/'+state.selected,options());$('#compare-result').innerHTML=`<p>Dry / fully available baseline: ${num(d.baseline.predicted_mt)} MT · scenario: ${num(d.active.predicted_mt)} MT · difference: ${num(d.delta_mt)} MT</p>${featureTable(d.drivers,['label','delta_mt'])}<p>${esc(d.method)}</p><button type="button" id="compare-export">Export comparison</button>`;$('#compare-export').onclick=()=>exportData('scenario-comparison',d)}catch(err){$('#compare-result').textContent=err.message}};$('#apply-comparison').onclick=()=>{if(!form.reportValidity())return;localStorage.setItem('mineos-scenario-'+state.selected,JSON.stringify(options()));render()}}

async function recoveryPanel(){const d=await api('/outcomes'+(state.selected?'?mine_id='+encodeURIComponent(state.selected):''));let host=$('#recovery-panel');if(!host){host=document.createElement('details');host.id='recovery-panel';host.className='panel';$('#content').append(host)}host.innerHTML=`<summary>Recovery register, outcomes and handover</summary><div class="metrics">${metric('Completed',d.summary.completed)}${metric('Recorded recovery',num(d.summary.actual_recovery_mt)+' MT')}${metric('Recorded action cost',money(d.summary.actual_cost_inr))}${metric('Estimated ROI',d.summary.estimated_roi==null?'No completed actions':num(d.summary.estimated_roi*100)+'%','Saved scenario rates; not audited profit')}</div><section class="panel"><div class="row"><select id="action-filter"><option value="all">All states</option>${['pending','acknowledged','accepted','rejected','completed'].map(v=>`<option>${v}</option>`).join('')}</select><button id="handover-export">Export handover JSON</button><button id="handover-print">Print / save PDF</button></div><div id="action-register"></div></section><section class="panel"><h2>Grade blending calculator</h2><p>Enter assay grades and tonnage to calculate a weighted blend estimate.</p><form id="blend"><div class="form-grid">${['tonnes_a','grade_a','tonnes_b','grade_b'].map(k=>`<label>${k}<input name="${k}" type="number" min="0" ${k.startsWith('grade')?'max="100"':''} step="any" required></label>`).join('')}</div><button>Calculate blended Mn %</button><p id="blend-result"></p></form></section>`;const draw=()=>{$('#action-register').innerHTML=d.rows.filter(r=>$('#action-filter').value==='all'||r.state===$('#action-filter').value).map(r=>`<article class="action"><h3>${esc(r.payload.title)}</h3>${badge(r.state)}<p>${esc(r.actor)} · ${esc(r.reason)}<br>Expected ${num(r.payload.extra_supply_mt)} MT; actual ${num(r.actual_recovered_mt)} MT</p>${r.state==='pending'?`<button data-action="${r.id}" data-state="acknowledged">Acknowledge</button>`:''}${['pending','acknowledged'].includes(r.state)?`<button data-action="${r.id}" data-state="accepted">Approve</button>`:''}${r.state==='accepted'?`<button data-action="${r.id}" data-state="completed">Record outcome</button><button data-action="${r.id}" data-state="rejected">Revoke</button>`:''}</article>`).join('')||'<p>No matching actions.</p>';$('#action-register').querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>actionDialog(b.dataset.action,b.dataset.state))};draw();$('#action-filter').onchange=draw;$('#handover-export').onclick=()=>exportData('shift-handover',d);$('#handover-print').onclick=()=>window.print();$('#blend').onsubmit=e=>{e.preventDefault();const v=Object.fromEntries([...new FormData(e.target)].map(([k,v])=>[k,Number(v)])),mass=v.tonnes_a+v.tonnes_b;$('#blend-result').textContent=mass?'Blended Mn '+num((v.tonnes_a*v.grade_a+v.tonnes_b*v.grade_b)/mass,2)+'% across '+num(mass)+' MT':'Enter a positive total mass.'}}

function polishSections(){

 const main=$('#content');if(!main||!main.querySelector('h1'))return;main.querySelector('.section-nav')?.remove();

 const titles=Array.from(main.querySelectorAll('h2')).filter(h=>!h.closest('details')&&!h.closest('#site-grid')&&!h.closest('#action-register')).slice(0,7);

 if(titles.length<2)return;

 const links=titles.map((h,i)=>{if(!h.id)h.id='section-heading-'+i;return '<a href="#'+h.id+'">'+esc(h.textContent)+'</a>'}).join('');

 const guide=document.createElement('nav');guide.className='section-nav';guide.setAttribute('aria-label','Sections on this page');guide.innerHTML='<strong>ON THIS PAGE</strong>'+links;

 const intro=main.querySelector('.sub');if(intro)intro.after(guide);

}

